apiVersion: v1
kind: ConfigMap
metadata:
  name: vikunja-cm
data:
  configFile: |
    auth:
      openid:
        enabled: true
        redirecturl: <path:argocd/data/argocd-vault-plugin/vikunja#redirecturl>
        providers:
          - name: <path:argocd/data/argocd-vault-plugin/vikunja#provider>
            authurl: <path:argocd/data/argocd-vault-plugin/vikunja#authurl>
            logouturl: <path:argocd/data/argocd-vault-plugin/vikunja#logouturl>
            clientid: <path:argocd/data/argocd-vault-plugin/vikunja#clientid>
            clientsecret: <path:argocd/data/argocd-vault-plugin/vikunja#clientsecret>