apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: kanbo
    app.kubernetes.io/instance: kanbo
  annotations:
    cert-manager.io/issuer: kanbo-letsencrypt    
  name: ingress
  namespace: kanbo
spec:
  ingressClassName: nginx 
  tls:
  - hosts:
    - <path:argocd/data/argocd-vault-plugin/vikunja#url>
    secretName: kanbo-tls
  rules:
  - host: <path:argocd/data/argocd-vault-plugin/vikunja#url>
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: kanbo-service
            port: 
              number: 443 #3456


