apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kanbo-letsencrypt
  namespace: kanbo
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: <path:argocd/data/argocd-vault-plugin/cloudflare#email>
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: kanbo-letsencrypt
    # ACME DNS-01 provider configurations
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector:
        dnsNames:
        - <path:argocd/data/argocd-vault-plugin/vikunja#url>
      dns01:
        cloudflare:
          email: <path:argocd/data/argocd-vault-plugin/cloudflare#email>
          # !! Remember to create a k8s secret before
          # kubectl create secret generic cloudflare-api-key-secret
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
