apiVersion: v1
kind: PersistentVolume
metadata:
  name: fv-pv
  labels:
    type: local
    app: vikunja-kanbo
spec:
  storageClassName: storage
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/nfs/app/vikunja"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: local
    app: vikunja-kanbo
spec:
  storageClassName: storage
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/nfs/app/vikunja"  
